apiVersion: apps/v1
kind: Deployment
metadata:
  name: test:19
spec:
  selector:
    matchLabels:
      app: test:19
  template:
    metadata:
      labels:
        app: test:19
    spec:
      containers:
      - name: test:19
        image: harshau04/test:19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
