apiVersion: apps/v1
kind: Deployment
metadata:
  name: test:18
spec:
  selector:
    matchLabels:
      app: test:18
  template:
    metadata:
      labels:
        app: test:18
    spec:
      containers:
      - name: test:18
        image: harshau04/test:18
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
