apiVersion: apps/v1
kind: Deployment
metadata:
  name: test:2
spec:
  selector:
    matchLabels:
      app: test:2
  template:
    metadata:
      labels:
        app: test:2
    spec:
      containers:
      - name: test:2
        image: harshau04/test:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
