name: Bug report ❗
description: Report a non-security sensitive bug or unexpected behavior
title: "[BUG] - <title>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: Provide a clear and concise description of what happend.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: How to Reproduce?
      description: Provide clear and concise steps to reproduce the problem.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
