name: Feature request
description: Request a new feature for this project
title: "[FEATURE] - <title>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the improvement
      description: Provide a clear and concise description of what the problem is and how we should solved that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do we need this?
      description: Provide a clear and concise description of what you want to happen and why the feature should be added.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
